### ISSUE TITLE
Port to mi 11

### ISSUE THREAD

**Issue by ghost** [senpaimaster05/recovery_builder#1]
Hi I wanted to check with you before moving forwards. Is it okay if I use your code as the basis to port twrp to the mi 11? Sorry for making an issue, but I couldn't find a better way to ask. Thank you.
https://github.com/senpaimaster05/twrp_device_xiaomi_star

**Comment by mastersenpai05** [comment]
Yes

**Comment by mastersenpai05** [comment]
> Hi I wanted to check with you before moving forwards. Is it okay if I use your code as the basis to port twrp to the mi 11? Sorry for making an issue, but I couldn't find a better way to ask. Thank you.
> https://github.com/senpaimaster05/twrp_device_xiaomi_star

Yes

**Comment by ghost** [comment]
Thank you very much!
